# Generated by Django 4.2.3 on 2023-07-28 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0011_alter_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance',
            field=models.ManyToManyField(related_name='attend', to=settings.AUTH_USER_MODEL),
        ),
    ]
